### PR TITLE
Refactoring of processing workflow.

### PR DESCRIPTION
**Pull request by simonpf**
- Switch to release version of quantnn which fixes issues with recent changes.
- Add option to reprocess failed input files from database.

### CODE REVIEW

**Comment by adriaat** [comment]
Is this WIP? If not, do you want me to review it?

**Comment by simonpf** [comment]
This PR refactors the processing workflow:
- Add '--transfer' option that allows copying of result files to a remote host
- The retrieval processing and writing of output files are now combined into one task but this task can executed by multiple processes in parallel. A lock is used to ensure that only one process at a time accesses the GPU.

**Comment by adriaat** [comment]
Great work.

Cool that you could figure out how get the environment file to install a PyTorch that would work with CUDA in one go; it seems to be quite sensitive.

I think there may still be some work left on fixing the packages required to have everything working as well as versions, c.f. setup.py and ccic.yml. But I don't think this is urgent at all, just nice to have. Therefore it would be good if you can export your development environment and save it under the common storage before anything 'bad' happens, e.g. your workstation crashes, like mine did; I can't do this since I have to rebuild everything from scratch.

Two notes:

- I see you define the containers as 'singularity containers'. I'm not sure which 'singularity' version you're using, but singularity was deprecated, with apptainer replacing it. I'm a bit confused now, since there are singularity forks, and a singularity community edition, and apptainer is the tool supported by the Linux Foundation. Apptainer treats singularity containers as a legacy and may not be supported in the future, I read. I would therefore just use the term apptainer everywhere, from now on, if we do any updates to the container scripts (and build the containers with apptainer).
- Is your email in setup.py still active?

See also the two small commits I added.

Out of curiosity: I couldn't follow why trim to [:32] characters the hash in ccic/bin/process.py:334, but then I noticed that most of the times the string is only 32 characters long anyway.

**Review by adriaat — APPROVED** [review]

**Comment by adriaat** [comment]
@simonpf, I can foresee an issue:

If I understand the code correctly, if the processing fails then we can run other passes by using the files downloaded previously by using the argument `--input-path` (the `tmp` dir will be destroyed after the job is over, I assume). However, it can happen that the processing fails because the downloaded file is, e.g., corrupted, i.e. cannot be read. I have experienced this and I expect this to happen. My approach was to quickly check each file if it could be read before starting the process with, e.g.,
```python
filenames = ["file1", "file2"]
failed = []
for f in filenames:
    try:
        _ = xr.open_dataset(f)
    except:
        failed.append(f)
```

I can't come up with any 'easy' solution, besides this: re-download any file that failed to process again, instead of using the previously downloaded ones.

I am merging since this issue I comment has a practical solution.

**Pull request merged**
